package io.github.leewyatt.rxcontrols.carousel.animation;

import io.github.leewyatt.rxcontrols.carousel.Direction;
import javafx.animation.Animation;
import javafx.animation.Interpolator;
import javafx.animation.KeyFrame;
import javafx.animation.KeyValue;
import javafx.animation.Timeline;
import javafx.beans.property.DoubleProperty;
import javafx.beans.property.SimpleDoubleProperty;
import javafx.beans.value.ChangeListener;
import javafx.scene.Node;
import javafx.scene.SnapshotParameters;
import javafx.scene.image.ImageView;
import javafx.scene.image.WritableImage;
import javafx.scene.layout.StackPane;
import javafx.scene.paint.Color;
import javafx.scene.shape.Polygon;
import javafx.util.Duration;

import java.util.ArrayList;
import java.util.List;
import java.util.Random;

/**
 * Shatter transition. The current page shatters into irregular triangular
 * fragments that fly outward, rotating, shrinking, and fading out to
 * reveal the next page beneath.
 *
 * <p>Fragments are generated by dividing the page into a grid, jittering
 * interior grid points for an irregular look, then splitting each cell
 * into two triangles along the diagonal.</p>
 *
 * <p>FORWARD adds a leftward bias to the flight direction and staggers
 * left-to-right; BACKWARD reverses both.</p>
 *
 * <p>Subclasses can override {@link #computeFlightData} to change how
 * fragments fly and stagger (e.g., radial explosion from a point).</p>
 *
 * <p><b>Note:</b> This animation uses snapshots and is not resize-safe.
 * If the carousel is resized during the animation, it will jump to its
 * end state automatically.</p>
 *
 * @see AnimShatterRadial
 */
public class AnimShatter extends CarouselAnimationBase {

    private final int cols;
    private final int rows;
    private Interpolator interpolator = Interpolator.EASE_IN;

    private final DoubleProperty progress = new SimpleDoubleProperty(0);
    private ChangeListener<Number> progressListener;

    private ImageView[] fragments;
    private double[] flightDx;
    private double[] flightDy;
    private double[] rotationTargets;
    private double[] delays;
    private StackPane animContentPane;

    /**
     * Creates a shatter animation with a 6x4 grid (48 fragments).
     */
    public AnimShatter() {
        this(6, 4);
    }

    /**
     * Creates a shatter animation with the given grid dimensions.
     * Total fragments = cols * rows * 2.
     *
     * @param cols number of grid columns (at least 1)
     * @param rows number of grid rows (at least 1)
     */
    public AnimShatter(int cols, int rows) {
        this.cols = Math.max(1, cols);
        this.rows = Math.max(1, rows);
    }

    /**
     * Returns the interpolator used for each fragment's flight.
     *
     * @return the interpolator
     */
    public Interpolator getInterpolator() {
        return interpolator;
    }

    /**
     * Sets the interpolator for each fragment's flight.
     *
     * @param interpolator the interpolator
     */
    public void setInterpolator(Interpolator interpolator) {
        this.interpolator = interpolator;
    }

    @Override
    public Animation getAnimation(TransitionContext context) {
        Node currentPage = context.getCurrentPage();
        Node nextPage = context.getNextPage();
        Duration duration = context.getDuration();
        Direction direction = context.getDirection();
        animContentPane = context.getContentPane();

        double w = animContentPane.getWidth();
        double h = animContentPane.getHeight();
        boolean forward = direction == Direction.FORWARD;

        installResizeGuard(animContentPane);

        if (nextPage != null) {
            nextPage.setVisible(true);
            nextPage.toBack();
        }

        SnapshotParameters params = new SnapshotParameters();
        params.setFill(Color.TRANSPARENT);

        WritableImage snap = currentPage != null ? currentPage.snapshot(params, null) : null;
        if (currentPage != null) {
            currentPage.setVisible(false);
        }

        // Generate jittered grid points
        Random rng = new Random();
        List<double[]> triangles = buildTriangles(w, h, rng);
        int fragCount = triangles.size();

        fragments = new ImageView[fragCount];
        flightDx = new double[fragCount];
        flightDy = new double[fragCount];
        rotationTargets = new double[fragCount];
        delays = new double[fragCount];

        double flightDistance = Math.sqrt(w * w + h * h) * 0.8;

        computeFlightData(triangles, w, h, forward, flightDistance,
                flightDx, flightDy, delays, rng);

        if (snap != null) {
            for (int i = 0; i < fragCount; i++) {
                double[] tri = triangles.get(i);

                rotationTargets[i] = (rng.nextDouble() * 2 - 1) * 180;

                ImageView frag = new ImageView(snap);
                frag.setManaged(false);

                Polygon clip = new Polygon(
                        tri[0], tri[1], tri[2], tri[3], tri[4], tri[5]);
                frag.setClip(clip);

                fragments[i] = frag;
                animContentPane.getChildren().add(frag);
            }
        }

        Runnable finish = () -> {
            removeResizeGuard();
            removeFragments();
            if (currentPage != null) {
                currentPage.setVisible(false);
            }
            if (nextPage != null) {
                nextPage.setVisible(true);
            }
        };
        setFinishAction(finish);

        context.fireClosing(context.getCurrentIndex());
        context.fireOpening(context.getNextIndex());

        if (progressListener != null) {
            progress.removeListener(progressListener);
        }
        progress.set(0);

        progressListener = (obs, oldVal, newVal) ->
                updateFragments(newVal.doubleValue());
        progress.addListener(progressListener);

        Timeline timeline = new Timeline(
                new KeyFrame(Duration.ZERO, new KeyValue(progress, 0)),
                new KeyFrame(duration,
                        new KeyValue(progress, 1, Interpolator.LINEAR))
        );

        timeline.setOnFinished(e -> {
            finish.run();
            context.fireClosed(context.getCurrentIndex());
            context.fireOpened(context.getNextIndex());
        });

        setCurrentAnimation(timeline);
        return timeline;
    }

    /**
     * Builds the jittered triangle grid from the page dimensions.
     *
     * @param w   the page width
     * @param h   the page height
     * @param rng the random number generator for grid jittering
     * @return a list of triangles, each as {@code [x0, y0, x1, y1, x2, y2]}
     */
    protected List<double[]> buildTriangles(double w, double h, Random rng) {
        double[][] gridX = new double[rows + 1][cols + 1];
        double[][] gridY = new double[rows + 1][cols + 1];
        double cellW = w / cols;
        double cellH = h / rows;
        double jitterX = cellW * 0.4;
        double jitterY = cellH * 0.4;

        for (int r = 0; r <= rows; r++) {
            for (int c = 0; c <= cols; c++) {
                double baseX = c * cellW;
                double baseY = r * cellH;
                boolean edge = (r == 0 || r == rows || c == 0 || c == cols);
                if (edge) {
                    gridX[r][c] = baseX;
                    gridY[r][c] = baseY;
                } else {
                    gridX[r][c] = baseX + (rng.nextDouble() * 2 - 1) * jitterX;
                    gridY[r][c] = baseY + (rng.nextDouble() * 2 - 1) * jitterY;
                }
            }
        }

        List<double[]> triangles = new ArrayList<>(cols * rows * 2);
        for (int r = 0; r < rows; r++) {
            for (int c = 0; c < cols; c++) {
                double x0 = gridX[r][c], y0 = gridY[r][c];
                double x1 = gridX[r][c + 1], y1 = gridY[r][c + 1];
                double x2 = gridX[r + 1][c + 1], y2 = gridY[r + 1][c + 1];
                double x3 = gridX[r + 1][c], y3 = gridY[r + 1][c];

                triangles.add(new double[]{x0, y0, x1, y1, x2, y2});
                triangles.add(new double[]{x0, y0, x2, y2, x3, y3});
            }
        }
        return triangles;
    }

    /**
     * Computes the flight vector (dx, dy) and stagger delay for each
     * fragment. Subclasses override this to change flight behavior.
     *
     * <p>The default implementation flies fragments outward from the page
     * center with a directional bias, staggered by horizontal position.</p>
     *
     * @param triangles     the triangle list from {@link #buildTriangles}
     * @param paneWidth     the content pane width
     * @param paneHeight    the content pane height
     * @param forward       true for FORWARD direction
     * @param flightDistance the maximum flight distance in pixels
     * @param flightDx      output array for X flight offsets
     * @param flightDy      output array for Y flight offsets
     * @param delays        output array for stagger delays (0.0 to ~0.4)
     * @param rng           random number generator
     */
    protected void computeFlightData(List<double[]> triangles,
                                      double paneWidth, double paneHeight,
                                      boolean forward, double flightDistance,
                                      double[] flightDx, double[] flightDy,
                                      double[] delays, Random rng) {
        double centerX = paneWidth / 2.0;
        double centerY = paneHeight / 2.0;
        double directionBias = forward ? -paneWidth * 0.3 : paneWidth * 0.3;

        for (int i = 0; i < triangles.size(); i++) {
            double[] tri = triangles.get(i);
            double cx = (tri[0] + tri[2] + tri[4]) / 3.0;
            double cy = (tri[1] + tri[3] + tri[5]) / 3.0;

            double dx = cx - centerX;
            double dy = cy - centerY;
            double len = Math.sqrt(dx * dx + dy * dy);
            if (len < 1) {
                len = 1;
            }
            flightDx[i] = (dx / len) * flightDistance + directionBias;
            flightDy[i] = (dy / len) * flightDistance;

            double normalizedX = forward ? cx / paneWidth : (paneWidth - cx) / paneWidth;
            delays[i] = normalizedX * 0.4;
        }
    }

    private void updateFragments(double p) {
        double flightDuration = 0.6;

        for (int i = 0; i < fragments.length; i++) {
            if (fragments[i] == null) {
                continue;
            }

            double localP = Math.max(0,
                    Math.min(1, (p - delays[i]) / flightDuration));
            double easedP = interpolator.interpolate(0.0, 1.0, localP);

            fragments[i].setTranslateX(flightDx[i] * easedP);
            fragments[i].setTranslateY(flightDy[i] * easedP);
            fragments[i].setRotate(rotationTargets[i] * easedP);
            fragments[i].setScaleX(1.0 - easedP);
            fragments[i].setScaleY(1.0 - easedP);
            fragments[i].setOpacity(1.0 - easedP);
        }
    }

    private void removeFragments() {
        if (fragments != null && animContentPane != null) {
            for (ImageView frag : fragments) {
                if (frag != null) {
                    frag.setClip(null);
                    frag.setImage(null);
                    animContentPane.getChildren().remove(frag);
                }
            }
        }
        fragments = null;
        flightDx = null;
        flightDy = null;
        rotationTargets = null;
        delays = null;
        animContentPane = null;
    }

    @Override
    public void clearEffects(TransitionContext context) {
        super.clearEffects(context);
        if (progressListener != null) {
            progress.removeListener(progressListener);
            progressListener = null;
        }
        removeFragments();
    }

    @Override
    public void dispose() {
        if (progressListener != null) {
            progress.removeListener(progressListener);
            progressListener = null;
        }
        removeFragments();
        super.dispose();
    }
}
